const data = {first_name: values?.first_name,
    last_name: values?.last_name,
    email: values?.email,
    phone_no: values?.phone_no,
    address_1: values?.address_1,
    address_2: values?.address_2,
    city: values?.city,
    state: values?.state,
    zip: values?.zip,
    country: values?.country,
    username: values?.username,
    customer_perm: values?.customer_perm,
    items_perm: values?.items_perm,
    item_kits_perm: values?.item_kits_perm,
    suppliers_perm: values?.suppliers_perm,
    reports_perm: values?.reports_perm,
    receivings_perm: values?.receivings_perm,
    sales_perm: values?.sales_perm,
    employees_perm: values?.employees_perm
};